"""Description of the change

Revision ID: 7e03959fbf7d
Revises: d3cf39b7fab0
Create Date: 2024-12-28 20:39:07.908095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e03959fbf7d'
down_revision: Union[str, None] = 'd3cf39b7fab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
