"""Initial migration: Create tables

Revision ID: d3cf39b7fab0
Revises: b434f48ca6dd
Create Date: 2024-12-28 20:38:42.015471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cf39b7fab0'
down_revision: Union[str, None] = 'b434f48ca6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
